<?php
ini_set('display_errors', 'On');
ini_set('display_startup_errors', 'On');
error_reporting(0);
define("INVALID_ADMIN_LOGIN", "Invalid username or Password.", true);
define("PROFILE_ADMIN_UPDATED", "Your profile has been updated successfully.", true);
define("FORGOT_PASSWD", "Password reset related email has been sent successfully.", true);
define("ADMIN_OLDPASSWORD","Please enter your old password.", true);
define("ADMIN_PASSWORD","Password has been changed successfully.", true);
define("USER_PASSWORD","Password has been updated successfully.", true);
define("USER_PASSWORD_USED","You have already changed the password!", true);
define("ADMIN_PASSWORDMATCH","Please enter same password.", true);
define("ADMIN_NOENTRY", "Sorry for the inconvenience!", true);
define("CONTENTADD", "	Record has been Added successfully.", true);
define("CONTENTUPDATE", "Record has been updated successfully.", true);
define("CONTENTDELETE", "Record has been deleted successfully.", true);
define("SENDING_DETAILS", "User has been created successfully.", true);
define("SENDING_ROLE", "Role has been created successfully.", true);
define("SENDING_DETAILSE", "User has been updated successfully.", true);
define("IMAGE_SIZE_LIMIT","Please upload image of size less than 1MB.",true);
define("IMAGE_UPDATED", "One record has been updated successfully.", true); 
define("IMAGE_DELETED", "One record has been deleted successfully.", true);
define("CATEGORY_ADD", "Category has been added successfully.", true);
define("CATEGORY_UPDATE", "Category has been updated successfully.", true);
define("CATEGORY_DELETE", "Category has been deleted successfully.", true);
define("CAT_CONTENTADD", "Category has been added successfully.", true);
define("CAT_CONTENTUPDATE", "Category has been updated successfully.", true);
define("IMAGE_DEL", "One record has been deleted successfully.", true);
define("CONTENTINACTIVE", "Content page has been deactivated successfully.", true);
define("ROLE_ADMIN_DACTIVE", "Role has been assigned successfully.", true);
define("PAGE_NOT_AUTHORIZED", "You are not authorized to access this page.", true);
define("LATEST_UPDATESADD", "Latest updates has been added successfully.", true);
define("LATEST_UPDATESUPDATE", "Latest updates has been updated successfully.", true);
define("LATEST_UPDATESDELETE", "Latest updates has been deleted successfully.", true);
define("LATEST_UPDATESINACTIVE", "Latest updates page has been deactivated successfully.", true);
define("CATEGORY_ONE", "One record has been deleted successfully.", true);
define("FEED_NOTIFICATION","Thank you for submitting feedback.", true);
define("FORM_NOTIFICATION","Your application has been submitted successfully.", true);
define("UPDATE","Record has been updated successfully.", true);
define("INSERT","Record has been Added successfully.", true);
define("DELETE", "Record has been deleted successfully.", true);
define("FEEDBACK", "Feedback Comment has been sent successfully.", true);
?>